version: '3.5'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=recipe
      - POSTGRES_DB=recipe
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGODB_DATABASE: recipe
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
